CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE sales
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    client_id  BIGINT,
    user_id    BIGINT,
    CONSTRAINT pk_sales PRIMARY KEY (id)
);

CREATE TABLE sale_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    BIGINT,
    quantity      INTEGER,
    price_at_sale DECIMAL,
    sale_id       BIGINT,
    CONSTRAINT pk_saleitems PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    unit_price  DECIMAL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    legal_name VARCHAR(255),
    cnpj       VARCHAR(255),
    email      VARCHAR(255),
    address    VARCHAR(255),
    phone      VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE invoices
(
    sale_id        BIGINT NOT NULL,
    invoice_number VARCHAR(255),
    generated_at   TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(255),
    nfe_reference  VARCHAR(255),
    xml_path       VARCHAR(255),
    danfe_path     VARCHAR(255),
    CONSTRAINT pk_invoices PRIMARY KEY (sale_id)
);

ALTER TABLE sales
    ADD CONSTRAINT FK_SALE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);

ALTER TABLE sales
    ADD CONSTRAINT FK_SALE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE sale_items
    ADD CONSTRAINT FK_SALEITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE sale_items
    ADD CONSTRAINT FK_SALEITEM_ON_SALE FOREIGN KEY (sale_id) REFERENCES sales (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICE_ON_SALE FOREIGN KEY (sale_id) REFERENCES sales (id);
