-- Step 1: Create the service_items table
CREATE TABLE service_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    unit_price  DECIMAL,
    duration    VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    active      BOOLEAN,
    CONSTRAINT pk_service_items PRIMARY KEY (id)
);

-- Step 2: Add the new foreign key column to the sale_items table
ALTER TABLE sale_items
    ADD COLUMN service_item_id BIGINT;

-- Step 3: Add the foreign key constraint to the sale_items table
ALTER TABLE sale_items
    ADD CONSTRAINT FK_SALEITEM_ON_SERVICEITEMS FOREIGN KEY (service_item_id) REFERENCES service_items (id);
