ALTER TABLE companies
    ADD COLUMN street VARCHAR(255) NOT NULL,
    ADD COLUMN number VARCHAR(255) NOT NULL,
    ADD COLUMN city VARCHAR(255) NOT NULL,
    ADD COLUMN state VARCHAR(255) NOT NULL,
    ADD COLUMN country VARCHAR(255) NOT NULL,
    ADD COLUMN zip_code VARCHAR(255) NOT NULL,
    ADD COLUMN complement VARCHAR(255),
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE;